spring:
  datasource:
    url: jdbc:mysql://211.87.178.170:3306/wxspcard_test
    username: wxspcard_test
    password: wxspcard_test
    test-while-idle: true
    validation-query: SELECT 1
  thymeleaf:
    mode: LEGACYHTML5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8088
app:
  id: wx1bec33ce046fb05a
  secrect: XA3Z5h8XuYp1UPALjfIJMADXRQLlwM1vfZW5Plu-vgQk8T8K6DV-O6JEEhsT6kpk
  agentid: 1000039
  key: derFTY2@!4